import httpx
import asyncio
import time

BASE_URL = "http://127.0.0.1:8000"

async def criar_aluno(cliente, aluno):
    resp = await cliente.post(
        f"{BASE_URL}/alunos", 
        json = {
                "nome":aluno.get("nome"), 
                "curso":aluno.get("curso"), 
                "IRA": aluno.get("IRA")
            }
        )
    #print("CRIAR: " + resp.json())

def listar_aluno():
    resp = httpx.get(f"{BASE_URL}/alunos")
    print(resp.json())

#simular vários clientes em paralelo
async def executar_em_paralelo():
    
    async with httpx.AsyncClient() as cliente:
        inicio = time.time()
        await asyncio.gather(
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5}),
            criar_aluno(cliente, {"nome":"Jefferson", "curso":"SI","IRA":4.5}),
            criar_aluno(cliente, {"nome":"Wladimir", "curso":"SI","IRA":7.5}),
            criar_aluno(cliente, {"nome":"Fábio", "curso":"SI","IRA":9.5})
        )
        fim = time.time()
        print(f"TOTAL: {fim-inicio} segundos")
    

if __name__ == "__main__":
   asyncio.run(executar_em_paralelo())