"""cria tabelas iniciais

Revision ID: 9c2510238130
Revises: 
Create Date: 2025-12-12 22:12:40.178086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c2510238130'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ator',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ator_nome'), 'ator', ['nome'], unique=False)
    op.create_table('diretor',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nacionalidade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diretor_nome'), 'diretor', ['nome'], unique=False)
    op.create_table('filme',
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('genero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('diretor_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diretor_id'], ['diretor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filme_titulo'), 'filme', ['titulo'], unique=False)
    op.create_table('filmeator',
    sa.Column('filme_id', sa.Integer(), nullable=False),
    sa.Column('ator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['ator.id'], ),
    sa.ForeignKeyConstraint(['filme_id'], ['filme.id'], ),
    sa.PrimaryKeyConstraint('filme_id', 'ator_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmeator')
    op.drop_index(op.f('ix_filme_titulo'), table_name='filme')
    op.drop_table('filme')
    op.drop_index(op.f('ix_diretor_nome'), table_name='diretor')
    op.drop_table('diretor')
    op.drop_index(op.f('ix_ator_nome'), table_name='ator')
    op.drop_table('ator')
    # ### end Alembic commands ###
